---
- hosts: solr
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
  handlers:
    - name: Restart solr
      service:
        name: solr
        state: restarted

  tasks:
    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
        
    # - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
    #   apt_repository:
    #     repo: ppa:nginx/stable

    # - name: Install java
    #   apt:
    #     name: openjdk-8-jdk
    #     state: present

    - name: Download solr
      get_url:
        url: "https://mirrors.estointernet.in/apache/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script 
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates= {{ solr_dir }}/bin/solr

    - name: Ensure Solr is started and enabled at boot
      service:
        name: solr
        state: started
        enabled: yes