---

- name: Install EPEL repo.
  yum:
    name: epel-release
    state: present

- name: Ensure firewall is stopped
  service:
    name: firewalld
    state: stopped

- name: Insatll nodejs and npm
  yum:
    name: npm
    state: present
    enablerepo: epel

- name: Install forever
  npm:
    name: forever
    global: yes
    state: present
